# SPDX-License-Identifier: MIT
#
# BITS theme untuk LuCI. SDK-compatible (feeds/luci).

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-theme-bits
LUCI_TITLE:=BITS
LUCI_PKGARCH:=all
LUCI_DEPENDS:=+luci-base +rpcd

PKG_LICENSE:=MIT
PKG_MAINTAINER:=Banten IT Solutions <support@bits.co.id>
PKG_VERSION:=1.0.3
PKG_RELEASE:=1

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature file