# SPDX-License-Identifier: MIT
#
# BITS theme untuk LuCI (24.10+). Dibangun lewat feeds/luci.
# Letakkan folder ini di feeds/luci/themes/luci-theme-bits.

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-theme-bits
LUCI_TITLE:=BITS
LUCI_PKGARCH:=all

PKG_LICENSE:=MIT
PKG_MAINTAINER:=Banten IT Solutions <support@bits.co.id>
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature file